### ISSUE TITLE
Consistant docstring formatting

### ISSUE THREAD

**Issue by scattenlaeufer** [scattenlaeufer/zapf-resotool#18]
There are many ways to format a docstring, but we should agree to use one. Four possible candidates would be:

* [reStructuredText](http://daouzli.com/blog/docstring.html#restructuredtext)
* [Numpydoc](http://daouzli.com/blog/docstring.html#numpydoc)
* [Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings)
* [Sphinx](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format)

Personally, I prefer reStructuredText because it's the most compact and the default setting for Python for vim-doge, but I'm open to other opinions.

**Comment by wagnersthub** [comment]
I think reStructuredText is okay.

**Comment by behrmann** [comment]
I don't particularly care, as long as there is an autoformatter.

**Comment by scattenlaeufer** [comment]
Ok, then let's use reStructuredText.
