### ISSUE TITLE
Mehrere Adressaten zu Gruppe zusammenfassen

### ISSUE THREAD

**Issue by ChrisBtt** [scattenlaeufer/zapf-resotool#24]
Resolutionen haben oft mehrere Empfängern, die oft zu einer Gruppe zusammen gefasst werden können. Beispielsweise werden alle Physikfachschaften in Deutschland oft genannt. 
Die Eingabe jeder einzelnen Physikfachschaft ist sehr lästig und kann dazu führen, dass einige Adressaten übersehen werden. 
Hier würde es sich anbieten, eine Gruppe von Empfängern zu erstellen, wo die einzelnen Adressaten dynamisch angepasst werden können.

**Comment by scattenlaeufer** [comment]
This is a duplicate of #3
